version: "3"
services:
  golang-postgres:
    image: postgres:14.0-alpine3.14 
    restart: always
    ports: 
      - 5431:5432
    volumes:
      - ./migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: golang-alura

volumes:
  postgres:

    